[WIP] Translate design/overview into ja
goadesign-jp/goa.design pull request #11
Opened 2017-01-06 09:22 UTC by ikawaha

2017-01-08 03:11 UTC, ikawaha commented
レビューお願いします

2017-01-08 03:43 UTC, tchssk requested changes

2017-01-08 03:43 UTC, tchssk commented on content/design/overview.ja.md
> +デザイン言語の主要部は、**定義** を記述するための関数の連鎖によって構成されています。
ここ **strong** になってますが、原文では *em* だったみたいなので合わせておきますか？

2017-01-08 04:12 UTC, tchssk commented on content/design/overview.ja.md
> +goa API デザイン言語はGoで実装されたDSLで、任意のマイクロサービスAPIを記述することができます。
全体的に英単語の前後にはスペースを入れるようにしましょうか。

2017-01-08 04:26 UTC, ikawaha commented
コメントもらった点を修正しました :bow:

2017-01-09 07:26 UTC, tchssk commented on content/design/overview.ja.md
> +この関数は、API が定義するメディアタイプも定義します。
`API が定義するメディアタイプ` は `API がサポートするメディアタイプ` でもいいかもしれませんね。

2017-01-09 07:29 UTC, tchssk commented on content/design/overview.ja.md
> +リソース関数は、関連する API エンドポイントのセットを定義します。
この `リソース` は関数名なので `Resource` ですね。

2017-01-09 07:30 UTC, tchssk requested changes

2017-01-09 07:30 UTC, tchssk commented on content/design/overview.ja.md
> +リソース関数は、関連する API エンドポイントのセットを定義します。
この `リソース` は関数名なので `Resource` ですね。

2017-01-09 07:32 UTC, tchssk requested changes

2017-01-09 07:32 UTC, tchssk commented on content/design/overview.ja.md
> +実際の各エンドポイントは、アクション関数を使用して記述されます。
この `アクション` は関数名なので `Action` ですね。

2017-01-09 07:33 UTC, tchssk requested changes

2017-01-09 07:33 UTC, tchssk commented on content/design/overview.ja.md
> +ここでは `add` アクションを(API エンドポイントとして)公開している単純な `Operand` リソースの例を示します。
`Operand` → `Operands`

2017-01-09 07:34 UTC, tchssk requested changes

2017-01-09 07:34 UTC, tchssk commented on content/design/overview.ja.md
> +リソース関数は任意の数のアクションを定義できます。
この `リソース` は関数名なので `Resource` ですね。

2017-01-09 07:35 UTC, tchssk requested changes

2017-01-09 07:35 UTC, tchssk commented on content/design/overview.ja.md
> +アクションパラメータを定義するために使用される DSL では、整数(integer)パラメータや数値(number)パラメータなら最小値と最大値、文字列パラメータでは正規表現をで定義されたバリデーションを指定できます：
`正規表現をで` → `正規表現で`

2017-01-09 08:59 UTC, ikawaha commented on content/design/overview.ja.md
> +リソース関数は、関連する API エンドポイントのセットを定義します。
修正します ('ー'ゝ

2017-01-09 08:59 UTC, ikawaha commented on content/design/overview.ja.md
> +実際の各エンドポイントは、アクション関数を使用して記述されます。
修正します('ー'ゝ

2017-01-09 08:59 UTC, ikawaha commented on content/design/overview.ja.md
> +ここでは `add` アクションを(API エンドポイントとして)公開している単純な `Operand` リソースの例を示します。
修正します('ー'ゝ

2017-01-09 08:59 UTC, ikawaha commented on content/design/overview.ja.md
> +リソース関数は任意の数のアクションを定義できます。
修正します('ー'ゝ

2017-01-09 09:00 UTC, ikawaha commented on content/design/overview.ja.md
> +アクションパラメータを定義するために使用される DSL では、整数(integer)パラメータや数値(number)パラメータなら最小値と最大値、文字列パラメータでは正規表現をで定義されたバリデーションを指定できます：
orz 修正します

2017-01-12 09:03 UTC, tchssk requested changes

2017-01-12 09:03 UTC, tchssk commented on content/design/overview.ja.md
> +`friend` フィールドを定義するのに `User` という変数を参照する代わりに、`"user"` という名前を使っていることに注意してください。
`friend` → `friends`

2017-01-12 09:03 UTC, tchssk commented on content/design/overview.ja.md
> +* **Link** は、レスポンスに埋め込んでレンダリングされる関連するメディアタイプにを表します。
`メディアタイプにを` → `メディアタイプを`

2017-01-12 12:54 UTC, tchssk approved these changes

2017-01-12 12:56 UTC, tchssk commented
ひととおりチェックしたのでこれでマージしますね。

2017-01-12 13:08 UTC, ikawaha commented
大変お手数かけてしましました．ありがとうございました :bow:

2017-01-12 13:12 UTC, merged