[WIP]Translate design/types into ja
goadesign-jp/goa.design pull request #12
Opened 2017-02-08 09:07 UTC by ikawaha

2017-02-13 07:39 UTC, tchssk requested changes

2017-02-13 07:39 UTC, tchssk commented on content/design/types.ja.md
> +もしくは事前にタイプを定義しておくことも可能です：
どちらかというと

```
もしくは事前に定義されたタイプを使用することもできます。
```

というニュアンスかと思いました。

2017-02-13 07:39 UTC, tchssk commented on content/design/types.ja.md
> +定義済みの型は、上記のように変数を使って参照することもできますし、名前で参照することも出来ます。
`型`ではなく`タイプ`とすると上の段落と合って良さそうです。

2017-02-13 07:39 UTC, tchssk commented on content/design/types.ja.md
> +デザイン言語には、[Overview](/design/overview) にリストされているいくつかのプリミティブ型が含まれていますが、[Type](http://goa.design/reference/goa/design/apidsl/#func-type-a-name-apidsl-type-a) 関数を使用して任意のデータ構造を再帰的に記述することができます。
`Overview` → `概要`

2017-02-13 07:39 UTC, tchssk commented on content/design/types.ja.md
> +詳細は、[Overview](/design/overview) を参照してください。
`Overview` → `概要`

2017-02-13 07:39 UTC, tchssk commented on content/design/types.ja.md
> +メディアタイプ定義では、依然として参照される Attribute の名前をリストする必要があることに注意してください。これにより、「継承する」Attribute を選別することが出来ます。。
`。。` → `。`

2017-02-13 07:39 UTC, tchssk commented on content/design/types.ja.md
> +## タイプとメディアタイプを混ぜあわせについて
`を` → `の`

2017-02-13 08:01 UTC, ikawaha commented
ありがとうございます！

2017-02-15 01:23 UTC, tchssk approved these changes

2017-02-15 01:24 UTC, merged