Translate design/vendoring into ja
goadesign-jp/goa.design pull request #16
Opened 2017-02-09 09:40 UTC by ikawaha

こんな風にできるの知らなかった．
（前見たときは glide の説明がペロッとあっただけだった）

2017-02-09 09:59 UTC, tchssk commented
翻訳駆動学習

2017-02-14 02:25 UTC, tchssk requested changes

2017-02-14 02:25 UTC, tchssk commented on content/design/vendoring.ja.md
> +上記の問題の症状は、使用しようとしているデザインが初期化されていないため、パニックで goagen がクラッシュすることです
英語版を修正したのでこちらにも反映お願いします。 https://github.com/goadesign/goa.design/pull/57#issuecomment-279587918

2017-02-22 06:35 UTC, tchssk requested changes

2017-02-22 06:35 UTC, tchssk commented on content/design/vendoring.ja.md
> +4. `glide install` を実行します
ここは手順なので「する」「される」「である」調で揃えてもいいかもしれません。

2017-02-22 06:35 UTC, tchssk commented on content/design/vendoring.ja.md
> +外部の従属関係をどのように取得する必要があるのかを見てください（ `external`に` e`と記されています）。
`従属関係` → `依存関係`

2017-02-22 07:01 UTC, ikawaha commented
コメントありがとうございます！こんな感じでどうですかね

2017-02-23 06:10 UTC, tchssk approved these changes

2017-02-23 06:10 UTC, merged

2017-02-23 06:13 UTC, tchssk commented
`/design` 終わったので `ja-design` ブランチは本家にマージしてもらって大丈夫ですね！

2017-02-23 06:41 UTC, ikawaha commented
🙌  ﾜｰ

( '-`).oO( もしかして tchssk さんが自分で本家にマージ可能？

2017-02-23 06:59 UTC, tchssk commented
確かに `Merge pull request` ボタンが押せるようになってました。
勝手なことはしたくないので今後そういう要請があればマージすることがあるかもですね！