Translate extend/generators into ja
goadesign-jp/goa.design pull request #37
Opened 2017-03-08 13:55 UTC by tchssk

2017-03-09 10:19 UTC, ikawaha requested changes

2017-03-09 10:19 UTC, ikawaha commented on content/extend/generators.ja.md
> +ジェネレータは DSL によって生成されたデータ構造を消費して成果物を生成します。ジェネレータは、既存の DSL と新しいDSL（新しい DSL の作成方法については [goa プラグイン DSL](/extend/dsls）を参照してください）用に記述することができます。生成する成果物は何でもかまいません。 DSL エンジンは生成の編成を提供し、実際の出力は認識しません。
![image](https://cloud.githubusercontent.com/assets/4232165/23731426/f7a5a52e-04b0-11e7-83c8-e1f1e7a3ced1.png)

手元でやるとリンクが生成できてない．なんでだろ

2017-03-09 10:19 UTC, ikawaha commented on content/extend/generators.ja.md
> +Writing Generators for the goa API DSL
Oops :)

2017-03-09 10:19 UTC, ikawaha commented on content/extend/generators.ja.md
> +この関数は、成功時には生成されたファイル名のリストを、それ以外の場合には解説的なエラーを返します。ジェネレータは、対応する DSL パッケージから直接 DSL 出力データ構造にアクセスします。例えば goa API DSL は、ビルドアップ API 定義を含む [APIDefinition](http://goa.design/reference/goa/design.html#type-api
リンクが無効・・・orz

2017-03-09 10:19 UTC, ikawaha commented on content/extend/generators.ja.md
> +goa DSL はまた、ユーザに定義されたものではなく、エンジンによって動的に生成されたメディアタイプのセットを含む [GeneratedMediaTypes](http://goa.design/reference/goa/design.html#variables:83772ba7ad0304b1562d08f190539946) を [Design](http://goa.design/r
リンクが・・・ orz

2017-03-09 10:19 UTC, ikawaha commented on content/extend/generators.ja.md
> +DSL エンジンパッケージは、メタデータ定義データ構造を定義します。
![image](https://cloud.githubusercontent.com/assets/4232165/23745105/5c0f3f2c-04fa-11e7-86a0-5dae9cdb8212.png)

手元だと表示が崩れてるけど，環境のせいか？

2017-03-10 07:47 UTC, tchssk commented on content/extend/generators.ja.md
> +この関数は、成功時には生成されたファイル名のリストを、それ以外の場合には解説的なエラーを返します。ジェネレータは、対応する DSL パッケージから直接 DSL 出力データ構造にアクセスします。例えば goa API DSL は、ビルドアップ API 定義を含む [APIDefinition](http://goa.design/reference/goa/design.html#type-api
原著もリンク切れてますね。一旦このままにしておいて、後ほど本家に対して英語・日本語両方修正する PR を投げます。

2017-03-10 07:48 UTC, ikawaha commented on content/extend/generators.ja.md
> +この関数は、成功時には生成されたファイル名のリストを、それ以外の場合には解説的なエラーを返します。ジェネレータは、対応する DSL パッケージから直接 DSL 出力データ構造にアクセスします。例えば goa API DSL は、ビルドアップ API 定義を含む [APIDefinition](http://goa.design/reference/goa/design.html#type-api
了解ですー

2017-03-10 07:51 UTC, tchssk commented on content/extend/generators.ja.md
> +Writing Generators for the goa API DSL
修正しました！ https://github.com/goadesign-jp/goa.design/pull/37/commits/cafa323e03b9f42e32e23f4f9e092269d923106c

2017-03-10 07:54 UTC, tchssk commented on content/extend/generators.ja.md
> +DSL エンジンパッケージは、メタデータ定義データ構造を定義します。
要らないリスト `-` が紛れ込んでいたので削除しました。 https://github.com/goadesign-jp/goa.design/pull/37/commits/72f640592b8aca1bb17c39a5e4537ac9203dc449

2017-03-10 07:57 UTC, tchssk commented on content/extend/generators.ja.md
> +ジェネレータは DSL によって生成されたデータ構造を消費して成果物を生成します。ジェネレータは、既存の DSL と新しいDSL（新しい DSL の作成方法については [goa プラグイン DSL](/extend/dsls）を参照してください）用に記述することができます。生成する成果物は何でもかまいません。 DSL エンジンは生成の編成を提供し、実際の出力は認識しません。
確固が全角になっていたからでした。 https://github.com/goadesign-jp/goa.design/pull/37/commits/4311612bc3da954b351e7e505352b69e35dfbbe2

2017-03-10 09:18 UTC, ikawaha commented on content/extend/generators.ja.md
> +DSL エンジンパッケージは、メタデータ定義データ構造を定義します。
これは
```
DSL エンジンパッケージは、メタデータ定義データ構造 MetadataDefinition を定義します。 
```
の意味なのかな？

2017-03-10 09:29 UTC, tchssk commented on content/extend/generators.ja.md
> +DSL エンジンパッケージは、メタデータ定義データ構造を定義します。
その意味ですね。修正しました。 https://github.com/goadesign-jp/goa.design/pull/37/commits/a7fb5f8a8e241325e7f2117e15de88a8fcc130ba

2017-03-10 10:01 UTC, ikawaha approved these changes

2017-03-10 10:01 UTC, ikawaha commented
修正＆チェックありがとうございました！

2017-03-10 10:02 UTC, merged