Translate extend/dsls into ja
goadesign-jp/goa.design pull request #39
Opened 2017-03-13 13:50 UTC by tchssk

このページはすごい分量でした。レビューも大変だと思いますがお願いします。

2017-03-14 01:40 UTC, ikawaha commented
これはすごい！
( '-`).oO( レビュー，少々お時間下さい

2017-03-14 14:30 UTC, ikawaha requested changes

2017-03-14 14:30 UTC, ikawaha commented on content/extend/dsls.ja.md
> +goa DSL は、*定義*と呼ばれる再帰的なデータ構造を構築する Go パッケージ関数で構成されています。これらの定義の根源は [Register](http://goa.design/reference/goa/dslengine/#func-register-a-name-dslengine-register-a:1e0eb94feca2c8be53d3bd77a1934133) 関数を介
`*定義*` のあとに空白が必要?

2017-03-14 14:30 UTC, ikawaha commented on content/extend/dsls.ja.md
> +新しい　DSL　を作成するときのパズルの最後のピースは、 DSL エンジンが実行する DSL *ルート*を定義することです。ルートは [Register](http://goa.design/reference/goa/dslengine.html#func-register-a-name-dslengine-register-a:1e0eb94feca2c8be53d3bd77a1934133
`*ルート*` のあとに空白が必要？

2017-03-14 14:31 UTC, ikawaha commented
大丈夫と思います 🙆 

リンクが切れてるところがあるのであとで修正をお願いします 🙇

2017-03-15 20:41 UTC, tchssk commented on content/extend/dsls.ja.md
> +goa DSL は、*定義*と呼ばれる再帰的なデータ構造を構築する Go パッケージ関数で構成されています。これらの定義の根源は [Register](http://goa.design/reference/goa/dslengine/#func-register-a-name-dslengine-register-a:1e0eb94feca2c8be53d3bd77a1934133) 関数を介
ありがとうございます。空白入れました。 https://github.com/goadesign-jp/goa.design/pull/39/commits/c0b4019038f7a555a564245637614d446e407522

2017-03-15 20:42 UTC, tchssk commented on content/extend/dsls.ja.md
> +新しい　DSL　を作成するときのパズルの最後のピースは、 DSL エンジンが実行する DSL *ルート*を定義することです。ルートは [Register](http://goa.design/reference/goa/dslengine.html#func-register-a-name-dslengine-register-a:1e0eb94feca2c8be53d3bd77a1934133
空白入れました。 c0b4019

2017-03-16 01:11 UTC, ikawaha approved these changes

2017-03-16 01:11 UTC, ikawaha commented
(๑˃̵ᴗ˂̵)و

2017-03-16 01:12 UTC, merged