Fix links of content/learn
goadesign-jp/goa.design pull request #51
Opened 2019-07-02 14:21 UTC by ikawaha

2019-07-02 15:01 UTC, tchssk requested changes

2019-07-02 15:01 UTC, tchssk commented on content/v1/learn/guide.ja.md
> +* `hrefs.go` はリソースの href を構築するためのグローバル関数を提供します。リソースの href によって、レスポンスが関連リソースにリンクすることが可能になります。goa は、リソースの「標準的な」アクション (デフォルトでは `show` アクション) の要求パスを調べることによって、これらの href をどのように構築するかを知ります。追加情報については [Action]
`https://goa.design` は不要

2019-07-02 15:14 UTC, ikawaha commented on content/v1/learn/guide.ja.md
> +* `hrefs.go` はリソースの href を構築するためのグローバル関数を提供します。リソースの href によって、レスポンスが関連リソースにリンクすることが可能になります。goa は、リソースの「標準的な」アクション (デフォルトでは `show` アクション) の要求パスを調べることによって、これらの href をどのように構築するかを知ります。追加情報については [Action]
ありがとうございます！修正しました．

2019-07-03 01:11 UTC, tchssk approved these changes

2019-07-03 01:11 UTC, merged